---
- name: Smoke test
  hosts: localhost
  tasks:
   - name: Collect basic information as part of smoke test
     purestorage.fusion.fusion_info:
      gather_subset: minimum
      issuer_id: "{{ ansible_env.FUSION_ISSUER_ID }}"
      private_key_file: "{{ ansible_env.FUSION_PRIVATE_KEY_FILE }}"
